### ISSUE TITLE
team 도메인 리팩토링

### ISSUE THREAD

**Issue by yeonjookang** [KUIT-CoNet/CoNet-Server-JPA#48]
## 상세 내용
- team 도메인 리팩토링 

## ToDo
- [ ] 컬렉션 join문 강의에서 배운대로 수정
- [x] teamService 클래스의 상수 추출
- [x] 코드 정렬
- [x] delete 문으로 수정
- [ ] API 테스트
